Description: >
  Creation of EKS cluster aka control plane
# The EKS cluster was created following the instruction here: https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html
Parameters:
  EnvironmentName:
    Type: String
    Default: udacitycapstone

Resources:
  myAmazonEKSClusterRole:
    Type: AWS::IAM::Role
    Description: >
      https://docs.aws.amazon.com/eks/latest/userguide/service_IAM_role.html
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
            # NOTE to self: This is eks.amazonaws.com AND NOT ec2.amazonaws.com
              Service:
                - eks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy


  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Version: "1.23"
      Name: !Sub ${EnvironmentName}-cluster
      RoleArn: !GetAtt myAmazonEKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${EnvironmentName}-ControlPlaneSG
        SubnetIds:
          Fn::Split:
            - ","
            - Fn::ImportValue: !Sub ${EnvironmentName}-PUB-NETS

Outputs:
  ClusterId:
    Description: EKS cluster id
    Value: !Ref EKSCluster
    Export:
      Name: !Sub ${EnvironmentName}-EKSCluster

  EKSRoleArn:
    Description: Role for accessing and creating aws resources
    Value: !GetAtt myAmazonEKSClusterRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-EKSRole
