version: 2.1

jobs:
  deploy-infrastructure:
    docker:
      - image: amazon/aws-cli
    parameters: &parameter
      project_id:
        type: string
        default: udacitycapstone
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yum install -y tar gzip
      # - run:
      #     name: Build the networks(VPC, Subnets etc)
      #     command: |
      #       aws cloudformation deploy \
      #         --template-file cloudformation/network.yml \
      #         --tags project=<< parameters.project_id >> \
      #         --stack-name "<< parameters.project_id >>-networks" \
      #         --parameter-overrides file://cloudformation/network-parameters.json
      - run:
          name: Create EKS Cluster
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/ekscluster.yml \
              --tags project=<< parameters.project_id >>\
              --stack-name "<< parameters.project_id >>-eks-cluster" \
              --capabilities CAPABILITY_NAMED_IAM
          no_output_timeout: 15m
      - run:
          name: Create Nodegroup exists
          command: |
            aws cloudformation deploy \
              --template-file cloudformation/eksnodegroup.yml \
              --tags project=<< parameters.project_id >> \
              --stack-name "<< parameters.project_id >>-eks-nodegroup" \
              --capabilities CAPABILITY_NAMED_IAM

workflows:
  workflowname:
    jobs:
      - deploy-infrastructure