---
- name: "Set up AWS configure and Kubectl updateconfig"
  hosts: management
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  environment:
    - AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"
    - AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"
    - AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION')}}"
    - AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN')}}"    
    - ENVIRONMENTNAME: udacitycapstone
  tasks:
    - name: Set aws_access_key_id
      shell: "aws configure set aws_access_key_id {{ AWS_ACCESS_KEY_ID }}"
    - name: Set aws_secret_access_key
      shell: "aws configure set aws_secret_access_key {{ AWS_SECRET_ACCESS_KEY }}"
    - name: Set aws_session_token
      shell: "aws configure set aws_session_token {{ AWS_SESSION_TOKEN }}"
    - name: Set aws_default_region
      shell: "aws configure set default.region {{ AWS_DEFAULT_REGION }}"
    - name: update kubeconfig file
      shell: "aws eks update-kubeconfig --region {{ AWS_DEFAULT_REGION }} --name ${ENVIRONMENTNAME}-cluster"