---
- name: "Create your running pods"
  hosts: management
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  environment:
    - AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"
    - AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"
    - AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION')}}"
    - AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN')}}"    
    - ENVIRONMENTNAME: udacitycapstone
  tasks:
    - name: running kubectl commands
      file:
        path: ~/kubernetes-files
        state: directory
        mode: 0755
    
    - name: copy files to kubernetes-files folder
      copy:
        src: cloudformation/webserver.yml
        dest: ~/kubernetes-files

    - name: deploy the pods
      shell:
        cmd: kubectl apply -f webserver.yml
        chdir: ~/kubernetes-files
