---
- name: "Create your running pods"
  hosts: management
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
  # when you ssh into a server, it ask you to answer yes/no/ blah blah... this [ansible_host_key_checking: false] switches that off or answers yes whatever it anyways prevent that from holding up your pipeline
    - ansible_host_key_checking: false
    - ansible_python_interpreter: /usr/bin/python
    - ansible_stdout_callback: yaml
    - AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"
    - AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"
    - AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION')}}"
    - AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN')}}"

  tasks:
    - name: running kubectl commands
      file:
        path: ~/kubernetes-files
        state: directory
        mode: 0755
    
    - name: copy files to kubernetes-files folder
      copy:
        src: webserver.yml
        dest: "~/kubernetes-files/webserver.yml"

    - name: deploy the pods
      shell:
        cmd: kubectl apply -f webserver.yml
        chdir: ~/kubernetes-files
