---
- name: "update pod image"
  hosts: management
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
  # when you ssh into a server, it ask you to answer yes/no/ blah blah... this [ansible_host_key_checking: false] switches that off or answers yes whatever it anyways prevent that from holding up your pipeline
    - ansible_host_key_checking: false
    - ansible_python_interpreter: /usr/bin/python
    - ansible_stdout_callback: yaml
    - AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"
    - AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY')}}"
    - AWS_DEFAULT_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION')}}"
    - AWS_SESSION_TOKEN: "{{ lookup('env', 'AWS_SESSION_TOKEN')}}"
    - docker_tag: "{{ lookup('env', 'CIRCLE_WORKFLOW_ID') }}"

  tasks:
    - name: update the image running in pods
      shell:
# These names- mlserver-deployment and mlservername -are from the deployment yaml file
        cmd: "kubectl set image deployment/mlserver-deployment mlimagename=daporubs/devopsmlapp:{{ docker_tag }}"
        chdir: ~/kubernetes-files

  