apiVersion: apps/v1 
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: mldeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mldeploy
  template:
    metadata:
      labels:
        app: mldeploy
    spec:
      containers:
      - name: mlserver
        image: daporubs/devopsmlapp:${CIRCLE_WORKFLOW_ID:0:7}
        ports: 
          - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: webserver-deployment-service
spec:
  selector:
    app: mldeploy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000